# Generated by Django 5.2.6 on 2025-09-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_task_priority_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='visibility',
            field=models.CharField(blank=True, choices=[('no_restrictions', 'No restrictions'), ('restricted', 'Restricted')], default='no_restrictions', max_length=20),
        ),
    ]
